### ISSUE TITLE
No icon for nighttime partly cloudy

### ISSUE THREAD

**Issue by grr** [inderdhir/DatWeatherDoe#44]
It's odd to see this icon 
![Partly cloudy](https://user-images.githubusercontent.com/690894/124231834-6eb2cc00-dad6-11eb-989b-c6a44241d65b.png)
in the middle of the night.

**Comment by inderdhir** [comment]
Fixed in 2.1.3!

**Comment by grr** [comment]
I'm using 2.1.3 and I haven't yet seen any the night time icons in the menubar. It's 3AM here and I'm seeing this:
<img width="88" alt="Screen Shot 2021-10-06 at 03 06 07" src="https://user-images.githubusercontent.com/690894/136164556-e00ca664-a050-4d20-81e2-c5defd47590c.png">

**Comment by grr** [comment]
been having bad weather here, so took a while to actually see some night icons, but i'm still seeing the daylight icons beuing used hours before sunrise. i don't have enough data points yet, but it looks like the either the data or the calculation to determine sunrise might be the cause.

**Comment by grr** [comment]
it's 1am and still seeing daylight icons, so it's probably not related to the sunrise calculation or data.

**Comment by inderdhir** [comment]
I have a fix up (#48), will test for a couple of days and cut a release if all goes well. Thanks for the help!
